# _config.yml

# Site Settings
title: "Node.js API guide"
description: "Simple guide to start writing a small test api"
baseurl: "/ node-api-guide eact-starter-guide"
url: "https://keacluster.github.io"

# Build Settings

# Other settings...
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
